---
- name: Build, Push, and Deploy Flask App to Kubernetes
  hosts: localhost
  connection: local

  vars:
    project_root: "{{ playbook_dir | dirname }}"
    image_name: flask-k8s
    image_tag: latest
    k8s_manifests_path: "{{ project_root }}/k8s"
    kube_config_path: ~/.kube/config

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ project_root }}"
      register: docker_build_result

    - name: Show Docker build output
      debug:
        var: docker_build_result

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', k8s_manifests_path + '/deployment.yaml') | from_yaml }}"
        kubeconfig: "{{ kube_config_path }}"

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', k8s_manifests_path + '/service.yaml') | from_yaml }}"
        kubeconfig: "{{ kube_config_path }}"

